version: "3"

services:
  hubot:
    container_name: hubot
    build: ./containers/hubot
    ports:
      - 8080:8080
    environment:
      HUBOT_SLACK_TOKEN: {ENV_SLACK_API_TOKEN}
      TESTCAFE_WEBHOOK_URL: "http://testcafe:8124/webhook/do-test"

  testcafe:
    container_name: testcafe
    build: ./containers/testcafe
    ports:
      - 1337:1337
      - 1338:1338
      - 8124:8124
    depends_on:
      - hubot
    environment:
      HUBOT_WEBHOOK_CONNECTION_URL: "http://hubot:8080/webhook/connection/random"
      HUBOT_WEBHOOK_REPORT_URL: "http://hubot:8080/webhook/report/random"
